import numpy as np
import pdb
import pandas as pd
import yaml
import logging
import sys
import datetime

from . import officers
from . import dispatches

log = logging.getLogger(__name__)


class UnknownFeatureError(Exception):
    def __init__(self, feature):
        self.feature = feature

    def __str__(self):
        return "Unknown feature: {}".format(self.feature)

def find_categorical_features(feature_list):
    """Given a list of feature names return the names of the
    features which are categorical

    Args:
        feature_list(list): list of feature names to check

    Returns:
        categorical_features(list): the features which are categorical
    """

    # TODO: make it so that we don't need to supply a bogus fake today to instantiate an OfficerFeature
    dummy_kwargs = {'to_date': '', 'from_date': '', 'fake_today':datetime.datetime.today(), 'table_name':'dummy_table'}
    feature_classes = [lookup(feature, **dummy_kwargs) for feature in feature_list]

    categorical_features = [feature.feature_name for feature in feature_classes if feature.is_categorical]

    return categorical_features


def find_label_features(feature_list):
    """Given a list of feature names return the names of the
    features which are labels

    Args:
        feature_list(list): list of feature names to check

    Returns:
        label_features(list): the features which are labels
    """

    # TODO: make it so that we don't need to supply a bogus fake today to instantiate an OfficerFeature
    dummy_kwargs = {'to_date': '', 'from_date': '', 'fake_today':datetime.datetime.today(), 'table_name':'dummy_table'}
    feature_classes = [lookup(feature, **dummy_kwargs) for feature in feature_list]

    label_features = [feature.feature_name for feature in feature_classes if feature.is_label]

    return label_features

def lookup(feature, **kwargs):

    if feature[1:3] == "yr":
        kwargs["feat_time_window"] = int(feature[0])
    else:
        kwargs["feat_time_window"] = 15

    dict_lookup = { 'AcademyScore': officers.AcademyScore(**kwargs),
                    'ArrestCount1Yr': officers.ArrestCount1Yr(**kwargs),
                    'ArrestCountCareer': officers.ArrestCountCareer(**kwargs),
                    'DivorceCount': officers.DivorceCount(**kwargs),
                    'SustainedRuleViolations': officers.SustainedRuleViolations(**kwargs),
                    'IncidentCount': officers.IncidentCount(**kwargs),
                    'MeanHoursPerShift': officers.MeanHoursPerShift(**kwargs),
                    'MilesFromPost': officers.MilesFromPost(**kwargs),
                    'OfficerGender': officers.OfficerGender(**kwargs),
                    'TimeGatedDummyFeature': officers.TimeGatedDummyFeature(**kwargs),
                    'OfficerRace': officers.OfficerRace(**kwargs),
                    'AllAllegations': officers.AllAllegations(**kwargs),
                    'LabelSustained': dispatches.LabelSustained(**kwargs),
                    'LabelUnjustified': dispatches.LabelUnjustified(**kwargs),
                    'LabelPreventable': dispatches.LabelPreventable(**kwargs),
                    'DispatchMinute': dispatches.DispatchMinute(**kwargs),
                    'DispatchHour': dispatches.DispatchHour(**kwargs),
                    'DispatchDayOfWeek': dispatches.DispatchDayOfWeek(**kwargs),
                    'DispatchYearQuarter': dispatches.DispatchYearQuarter(**kwargs),
                    'DispatchMonth': dispatches.DispatchMonth(**kwargs),
                    'DispatchYear': dispatches.DispatchYear(**kwargs),
                    'OriginalPriority': dispatches.OriginalPriority(**kwargs),
                    'DispatchType': dispatches.DispatchType(**kwargs),
                    'DispatchSubType': dispatches.DispatchSubType(**kwargs),
                    'NumberOfUnitsAssigned': dispatches.NumberOfUnitsAssigned(**kwargs),
                    'AverageOfficerTravelTime': dispatches.AverageOfficerTravelTime(**kwargs),
                    'MinimumOfficerTravelTime': dispatches.MinimumOfficerTravelTime(**kwargs),
                    'MaximumOfficerTravelTime': dispatches.MaximumOfficerTravelTime(**kwargs),
                    'DispatchCategory': dispatches.DispatchCategory(**kwargs),
                    'ArrestsInPast1Hour': dispatches.ArrestsInPast1Hour(**kwargs),
                    'ArrestsInPast6Hours': dispatches.ArrestsInPast6Hours(**kwargs),
                    'ArrestsInPast12Hours': dispatches.ArrestsInPast12Hours(**kwargs),
                    'ArrestsInPast24Hours': dispatches.ArrestsInPast24Hours(**kwargs),
                    'ArrestsInPast48Hours': dispatches.ArrestsInPast48Hours(**kwargs),
                    'ArrestsInPastWeek': dispatches.ArrestsInPastWeek(**kwargs),
                    'FelonyArrestsInPast1Hour': dispatches.FelonyArrestsInPast1Hour(**kwargs),
                    'FelonyArrestsInPast6Hours': dispatches.FelonyArrestsInPast6Hours(**kwargs),
                    'FelonyArrestsInPast12Hours': dispatches.FelonyArrestsInPast12Hours(**kwargs),
                    'FelonyArrestsInPast24Hours': dispatches.FelonyArrestsInPast24Hours(**kwargs),
                    'FelonyArrestsInPast48Hours': dispatches.FelonyArrestsInPast48Hours(**kwargs),
                    'FelonyArrestsInPastWeek': dispatches.FelonyArrestsInPastWeek(**kwargs),
                    'DrugsArrestsInPast1Hour': dispatches.DrugsArrestsInPast1Hour(**kwargs),
                    'DrugsArrestsInPast6Hours': dispatches.DrugsArrestsInPast6Hours(**kwargs),
                    'DrugsArrestsInPast12Hours': dispatches.DrugsArrestsInPast12Hours(**kwargs),
                    'DrugsArrestsInPast24Hours': dispatches.DrugsArrestsInPast24Hours(**kwargs),
                    'DrugsArrestsInPast48Hours': dispatches.DrugsArrestsInPast48Hours(**kwargs),
                    'DrugsArrestsInPastWeek': dispatches.DrugsArrestsInPastWeek(**kwargs),
                    'StolenVehicleArrestsInPast1Hour': dispatches.StolenVehicleArrestsInPast1Hour(**kwargs),
                    'StolenVehicleArrestsInPast6Hours': dispatches.StolenVehicleArrestsInPast6Hours(**kwargs),
                    'StolenVehicleArrestsInPast12Hours': dispatches.StolenVehicleArrestsInPast12Hours(**kwargs),
                    'StolenVehicleArrestsInPast24Hours': dispatches.StolenVehicleArrestsInPast24Hours(**kwargs),
                    'StolenVehicleArrestsInPast48Hours': dispatches.StolenVehicleArrestsInPast48Hours(**kwargs),
                    'StolenVehicleArrestsInPastWeek': dispatches.StolenVehicleArrestsInPastWeek(**kwargs),
                    'OfficersDispatchedInPast1Minute': dispatches.OfficersDispatchedInPast1Minute(**kwargs),
                    'OfficersDispatchedInPast15Minutes': dispatches.OfficersDispatchedInPast15Minutes(**kwargs),
                    'OfficersDispatchedInPast30Minutes': dispatches.OfficersDispatchedInPast30Minutes(**kwargs),
                    'OfficersDispatchedInPast1Hour': dispatches.OfficersDispatchedInPast1Hour(**kwargs),
                    'OfficersDispatchedAverageUnjustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedAverageUnjustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedAverageJustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedAverageJustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedAveragePreventableIncidentsInPast3Years': dispatches.OfficersDispatchedAveragePreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedAverageNonPreventableIncidentsInPast3Years': dispatches.OfficersDispatchedAverageNonPreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedAverageSustainedAllegationsInPast3Years': dispatches.OfficersDispatchedAverageSustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedAverageUnsustainedAllegationsInPast3Years': dispatches.OfficersDispatchedAverageUnsustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedAverageUnjustifiedIncidentsInPastYear': dispatches.OfficersDispatchedAverageUnjustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedAverageJustifiedIncidentsInPastYear': dispatches.OfficersDispatchedAverageJustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedAveragePreventableIncidentsInPastYear': dispatches.OfficersDispatchedAveragePreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedAverageNonPreventableIncidentsInPastYear': dispatches.OfficersDispatchedAverageNonPreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedAverageSustainedAllegationsInPastYear': dispatches.OfficersDispatchedAverageSustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedAverageUnsustainedAllegationsInPastYear': dispatches.OfficersDispatchedAverageUnsustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedAverageUnjustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedAverageUnjustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedAverageJustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedAverageJustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedAveragePreventableIncidentsInPast6Months': dispatches.OfficersDispatchedAveragePreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedAverageNonPreventableIncidentsInPast6Months': dispatches.OfficersDispatchedAverageNonPreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedAverageSustainedAllegationsInPast6Months': dispatches.OfficersDispatchedAverageSustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedAverageUnsustainedAllegationsInPast6Months': dispatches.OfficersDispatchedAverageUnsustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedAverageUnjustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedAverageUnjustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedAverageJustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedAverageJustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedAveragePreventableIncidentsInPast1Month': dispatches.OfficersDispatchedAveragePreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedAverageNonPreventableIncidentsInPast1Month': dispatches.OfficersDispatchedAverageNonPreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedAverageSustainedAllegationsInPast1Month': dispatches.OfficersDispatchedAverageSustainedAllegationsInPast1Month(**kwargs),
                    'OfficersDispatchedAverageUnsustainedAllegationsInPast1Month': dispatches.OfficersDispatchedAverageUnsustainedAllegationsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumUnjustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedMinimumUnjustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumJustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedMinimumJustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumPreventableIncidentsInPast3Years': dispatches.OfficersDispatchedMinimumPreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumNonPreventableIncidentsInPast3Years': dispatches.OfficersDispatchedMinimumNonPreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumSustainedAllegationsInPast3Years': dispatches.OfficersDispatchedMinimumSustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumUnsustainedAllegationsInPast3Years': dispatches.OfficersDispatchedMinimumUnsustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedMinimumUnjustifiedIncidentsInPastYear': dispatches.OfficersDispatchedMinimumUnjustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumJustifiedIncidentsInPastYear': dispatches.OfficersDispatchedMinimumJustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumPreventableIncidentsInPastYear': dispatches.OfficersDispatchedMinimumPreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumNonPreventableIncidentsInPastYear': dispatches.OfficersDispatchedMinimumNonPreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumSustainedAllegationsInPastYear': dispatches.OfficersDispatchedMinimumSustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumUnsustainedAllegationsInPastYear': dispatches.OfficersDispatchedMinimumUnsustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedMinimumUnjustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedMinimumUnjustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumJustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedMinimumJustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumPreventableIncidentsInPast6Months': dispatches.OfficersDispatchedMinimumPreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumNonPreventableIncidentsInPast6Months': dispatches.OfficersDispatchedMinimumNonPreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumSustainedAllegationsInPast6Months': dispatches.OfficersDispatchedMinimumSustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumUnsustainedAllegationsInPast6Months': dispatches.OfficersDispatchedMinimumUnsustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedMinimumUnjustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedMinimumUnjustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumJustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedMinimumJustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumPreventableIncidentsInPast1Month': dispatches.OfficersDispatchedMinimumPreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumNonPreventableIncidentsInPast1Month': dispatches.OfficersDispatchedMinimumNonPreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumSustainedAllegationsInPast1Month': dispatches.OfficersDispatchedMinimumSustainedAllegationsInPast1Month(**kwargs),
                    'OfficersDispatchedMinimumUnsustainedAllegationsInPast1Month': dispatches.OfficersDispatchedMinimumUnsustainedAllegationsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumUnjustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedMaximumUnjustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumJustifiedIncidentsInPast3Years': dispatches.OfficersDispatchedMaximumJustifiedIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumPreventableIncidentsInPast3Years': dispatches.OfficersDispatchedMaximumPreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumNonPreventableIncidentsInPast3Years': dispatches.OfficersDispatchedMaximumNonPreventableIncidentsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumSustainedAllegationsInPast3Years': dispatches.OfficersDispatchedMaximumSustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumUnsustainedAllegationsInPast3Years': dispatches.OfficersDispatchedMaximumUnsustainedAllegationsInPast3Years(**kwargs),
                    'OfficersDispatchedMaximumUnjustifiedIncidentsInPastYear': dispatches.OfficersDispatchedMaximumUnjustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumJustifiedIncidentsInPastYear': dispatches.OfficersDispatchedMaximumJustifiedIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumPreventableIncidentsInPastYear': dispatches.OfficersDispatchedMaximumPreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumNonPreventableIncidentsInPastYear': dispatches.OfficersDispatchedMaximumNonPreventableIncidentsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumSustainedAllegationsInPastYear': dispatches.OfficersDispatchedMaximumSustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumUnsustainedAllegationsInPastYear': dispatches.OfficersDispatchedMaximumUnsustainedAllegationsInPastYear(**kwargs),
                    'OfficersDispatchedMaximumUnjustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedMaximumUnjustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumJustifiedIncidentsInPast6Months': dispatches.OfficersDispatchedMaximumJustifiedIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumPreventableIncidentsInPast6Months': dispatches.OfficersDispatchedMaximumPreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumNonPreventableIncidentsInPast6Months': dispatches.OfficersDispatchedMaximumNonPreventableIncidentsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumSustainedAllegationsInPast6Months': dispatches.OfficersDispatchedMaximumSustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumUnsustainedAllegationsInPast6Months': dispatches.OfficersDispatchedMaximumUnsustainedAllegationsInPast6Months(**kwargs),
                    'OfficersDispatchedMaximumUnjustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedMaximumUnjustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumJustifiedIncidentsInPast1Month': dispatches.OfficersDispatchedMaximumJustifiedIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumPreventableIncidentsInPast1Month': dispatches.OfficersDispatchedMaximumPreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumNonPreventableIncidentsInPast1Month': dispatches.OfficersDispatchedMaximumNonPreventableIncidentsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumSustainedAllegationsInPast1Month': dispatches.OfficersDispatchedMaximumSustainedAllegationsInPast1Month(**kwargs),
                    'OfficersDispatchedMaximumUnsustainedAllegationsInPast1Month': dispatches.OfficersDispatchedMaximumUnsustainedAllegationsInPast1Month(**kwargs),
                    'AverageAgeOfRespondingOfficers': dispatches.AverageAgeOfRespondingOfficers(**kwargs),
                    'MaximumAgeOfRespondingOfficers': dispatches.MaximumAgeOfRespondingOfficers(**kwargs),
                    'MinimumAgeOfRespondingOfficers': dispatches.MinimumAgeOfRespondingOfficers(**kwargs),
                    'HighestEducationLevelAmongRespondingOfficers': dispatches.HighestEducationLevelAmongRespondingOfficers(**kwargs),
                    'LowestEducationLevelAmongRespondingOfficers': dispatches.LowestEducationLevelAmongRespondingOfficers(**kwargs),
                    'ProportionOfRespondingOfficersWithFourYearCollegeDegreeOrHigher': dispatches.ProportionOfRespondingOfficersWithFourYearCollegeDegreeOrHigher(**kwargs),
                    'ProportionOfRespondingOfficersMale': dispatches.ProportionOfRespondingOfficersMale(**kwargs),
                    'ProportionOfRespondingOfficersBlack': dispatches.ProportionOfRespondingOfficersBlack(**kwargs),
                    'ProportionOfRespondingOfficersHispanic': dispatches.ProportionOfRespondingOfficersHispanic(**kwargs),
                    'ProportionOfRespondingOfficersAsian': dispatches.ProportionOfRespondingOfficersAsian(**kwargs),
                    'ProportionOfRespondingOfficersOtherRace': dispatches.ProportionOfRespondingOfficersOtherRace(**kwargs),
                    'ProportionOfRespondingOfficersDivorcedOrSeparated': dispatches.ProportionOfRespondingOfficersDivorcedOrSeparated(**kwargs),
                    'ProportionOfRespondingOfficersMarried': dispatches.ProportionOfRespondingOfficersMarried(**kwargs),
                    'MedianAgeInCT': dispatches.MedianAgeInCT(**kwargs),
                    'MedianAgeOfMenInCT': dispatches.MedianAgeOfMenInCT(**kwargs),
                    'MedianAgeOfWomenInCT': dispatches.MedianAgeOfWomenInCT(**kwargs),
                    'UnweightedSampleCountOfPopulationInCT': dispatches.UnweightedSampleCountOfPopulationInCT(**kwargs),
                    'UnweightedSampleCountOfHousingUnitsInCT': dispatches.UnweightedSampleCountOfHousingUnitsInCT(**kwargs),
                    'PercentageMenInCT': dispatches.PercentageMenInCT(**kwargs),
                    'PercentageWomenInCT': dispatches.PercentageWomenInCT(**kwargs),
                    'PercentageWhiteInCT': dispatches.PercentageWhiteInCT(**kwargs),
                    'PercentageBlackInCT': dispatches.PercentageBlackInCT(**kwargs),
                    'PercentageAsianInCT': dispatches.PercentageAsianInCT(**kwargs),
                    'PercentageHispanicInCT': dispatches.PercentageHispanicInCT(**kwargs),
                    'PercentageForeignBornInCT': dispatches.PercentageForeignBornInCT(**kwargs),
                    'ProportionOfPopulationUnderAge18InCT': dispatches.ProportionOfPopulationUnderAge18InCT(**kwargs),
                    'ProportionOfPopulationEnrolledInSchoolInCT': dispatches.ProportionOfPopulationEnrolledInSchoolInCT(**kwargs),
                    'ProportionOfPopulationOver25WithLessThanHighSchoolEducationInCT': dispatches.ProportionOfPopulationOver25WithLessThanHighSchoolEducationInCT(**kwargs),
                    'ProportionOfPopulationVeteransInCT': dispatches.ProportionOfPopulationVeteransInCT(**kwargs),
                    'ProportionOfPopulationWithIncomeBelowPovertyLevelInPastYearInCT': dispatches.ProportionOfPopulationWithIncomeBelowPovertyLevelInPastYearInCT(**kwargs),
                    'ProportionOfPopulationWithIncomeInPast12MonthsBelow45000DollarsInCT': dispatches.ProportionOfPopulationWithIncomeInPast12MonthsBelow45000DollarsInCT(**kwargs),
                    'MedianIncomeInPast12MonthsInCT': dispatches.MedianIncomeInPast12MonthsInCT(**kwargs),
                    'MedianHouseholdIncomeInPast12MonthsInCT': dispatches.MedianHouseholdIncomeInPast12MonthsInCT(**kwargs),
                    'ProportionOfHouseholdsReceivingAssistanceOrFoodStampsInCT': dispatches.ProportionOfHouseholdsReceivingAssistanceOrFoodStampsInCT(**kwargs),
                    'ProportionOfHousingUnitsVacantInCT': dispatches.ProportionOfHousingUnitsVacantInCT(**kwargs),
                    'ProportionOfHousingUnitsOccupiedByOwnerInCT': dispatches.ProportionOfHousingUnitsOccupiedByOwnerInCT(**kwargs),
                    'MedianYearStructureBuildInCT': dispatches.MedianYearStructureBuildInCT(**kwargs),
                    'MedianYearRenterMovedIntoHousingUnitInCT': dispatches.MedianYearRenterMovedIntoHousingUnitInCT(**kwargs),
                    'MedianYearOwnerMovedIntoHousingUnitInCT': dispatches.MedianYearOwnerMovedIntoHousingUnitInCT(**kwargs),
                    'MedianGrossRentInCT': dispatches.MedianGrossRentInCT(**kwargs),
                    'MedianPropertyValueInCT': dispatches.MedianPropertyValueInCT(**kwargs),
                    'LowerQuartilePropertyValueInCT': dispatches.LowerQuartilePropertyValueInCT(**kwargs),
                    'UpperQuartilePropertyValueInCT': dispatches.UpperQuartilePropertyValueInCT(**kwargs),
                    'AverageHouseholdSizeInCT': dispatches.AverageHouseholdSizeInCT(**kwargs),
                    'ProportionOfChildrenUnder18LivingWithSingleParentInCT': dispatches.ProportionOfChildrenUnder18LivingWithSingleParentInCT(**kwargs),
                    'ProportionOfChildrenUnder18LivingWithMotherInCT': dispatches.ProportionOfChildrenUnder18LivingWithMotherInCT(**kwargs),
                    'ProportionOfPopulationNeverMarriedInCT': dispatches.ProportionOfPopulationNeverMarriedInCT(**kwargs),
                    'ProportionOfPopulationDivorcedOrSeparatedInCT': dispatches.ProportionOfPopulationDivorcedOrSeparatedInCT(**kwargs),
                    'ProportionOfPopulationWithoutHealthInsuranceInCT': dispatches.ProportionOfPopulationWithoutHealthInsuranceInCT(**kwargs),
                    'ProportionOfWomenWhoGaveBirthInPast12MonthsInCT': dispatches.ProportionOfWomenWhoGaveBirthInPast12MonthsInCT(**kwargs),
                    'ArrestsWithin1kmRadiusInPast1Hour': dispatches.ArrestsWithin1kmRadiusInPast1Hour(**kwargs),
                    'ArrestsWithin1kmRadiusInPast6Hours': dispatches.ArrestsWithin1kmRadiusInPast6Hours(**kwargs),
                    'ArrestsWithin1kmRadiusInPast12Hours': dispatches.ArrestsWithin1kmRadiusInPast12Hours(**kwargs),
                    'ArrestsWithin1kmRadiusInPast24Hours': dispatches.ArrestsWithin1kmRadiusInPast24Hours(**kwargs),
                    'ArrestsWithin500mRadiusInPast1Hour': dispatches.ArrestsWithin500mRadiusInPast1Hour(**kwargs),
                    'ArrestsWithin500mRadiusInPast6Hours': dispatches.ArrestsWithin500mRadiusInPast6Hours(**kwargs),
                    'ArrestsWithin500mRadiusInPast12Hours': dispatches.ArrestsWithin500mRadiusInPast12Hours(**kwargs),
                    'ArrestsWithin500mRadiusInPast24Hours': dispatches.ArrestsWithin500mRadiusInPast24Hours(**kwargs),
                    'ArrestsWithin100mRadiusInPast1Hour': dispatches.ArrestsWithin100mRadiusInPast1Hour(**kwargs),
                    'ArrestsWithin100mRadiusInPast6Hours': dispatches.ArrestsWithin100mRadiusInPast6Hours(**kwargs),
                    'ArrestsWithin100mRadiusInPast12Hours': dispatches.ArrestsWithin100mRadiusInPast12Hours(**kwargs),
                    'ArrestsWithin100mRadiusInPast24Hours': dispatches.ArrestsWithin100mRadiusInPast24Hours(**kwargs),
                    'DispatchesWithin1kmRadiusInPast15Minutes': dispatches.DispatchesWithin1kmRadiusInPast15Minutes(**kwargs),
                    'DispatchesWithin1kmRadiusInPast30Minutes': dispatches.DispatchesWithin1kmRadiusInPast30Minutes(**kwargs),
                    'DispatchesWithin1kmRadiusInPast1Hour': dispatches.DispatchesWithin1kmRadiusInPast1Hour(**kwargs),
                    'DispatchesWithin500mRadiusInPast15Minutes': dispatches.DispatchesWithin500mRadiusInPast15Minutes(**kwargs),
                    'DispatchesWithin500mRadiusInPast30Minutes': dispatches.DispatchesWithin500mRadiusInPast30Minutes(**kwargs),
                    'DispatchesWithin500mRadiusInPast1Hour': dispatches.DispatchesWithin500mRadiusInPast1Hour(**kwargs),
                    'DispatchesWithin100mRadiusInPast15Minutes': dispatches.DispatchesWithin100mRadiusInPast15Minutes(**kwargs),
                    'DispatchesWithin100mRadiusInPast30Minutes': dispatches.DispatchesWithin100mRadiusInPast30Minutes(**kwargs),
                    'DispatchesWithin100mRadiusInPast1Hour': dispatches.DispatchesWithin100mRadiusInPast1Hour(**kwargs),
                    'AverageOfficerDispatchesWithin100mRadiusInPast1Hour': dispatches.AverageOfficerDispatchesWithin100mRadiusInPast1Hour(**kwargs),
                    'AverageOfficerDispatchesWithin100mRadiusInPast3Hours': dispatches.AverageOfficerDispatchesWithin100mRadiusInPast3Hours(**kwargs),
                    'AverageOfficerDispatchesWithin100mRadiusInPast6Hours': dispatches.AverageOfficerDispatchesWithin100mRadiusInPast6Hours(**kwargs),
                    'AverageOfficerDispatchesWithin100mRadiusInPast24Hours': dispatches.AverageOfficerDispatchesWithin100mRadiusInPast24Hours(**kwargs),
                    'AverageOfficerDispatchesWithin100mRadiusInPast48Hours': dispatches.AverageOfficerDispatchesWithin100mRadiusInPast48Hours(**kwargs),
                    'AverageOfficerDispatchesWithin500mRadiusInPast1Hour': dispatches.AverageOfficerDispatchesWithin500mRadiusInPast1Hour(**kwargs),
                    'AverageOfficerDispatchesWithin500mRadiusInPast3Hours': dispatches.AverageOfficerDispatchesWithin500mRadiusInPast3Hours(**kwargs),
                    'AverageOfficerDispatchesWithin500mRadiusInPast6Hours': dispatches.AverageOfficerDispatchesWithin500mRadiusInPast6Hours(**kwargs),
                    'AverageOfficerDispatchesWithin500mRadiusInPast24Hours': dispatches.AverageOfficerDispatchesWithin500mRadiusInPast24Hours(**kwargs),
                    'AverageOfficerDispatchesWithin500mRadiusInPast48Hours': dispatches.AverageOfficerDispatchesWithin500mRadiusInPast48Hours(**kwargs),
                    'AverageOfficerDispatchesWithin1kmRadiusInPast1Hour': dispatches.AverageOfficerDispatchesWithin1kmRadiusInPast1Hour(**kwargs),
                    'AverageOfficerDispatchesWithin1kmRadiusInPast3Hours': dispatches.AverageOfficerDispatchesWithin1kmRadiusInPast3Hours(**kwargs),
                    'AverageOfficerDispatchesWithin1kmRadiusInPast6Hours': dispatches.AverageOfficerDispatchesWithin1kmRadiusInPast6Hours(**kwargs),
                    'AverageOfficerDispatchesWithin1kmRadiusInPast24Hours': dispatches.AverageOfficerDispatchesWithin1kmRadiusInPast24Hours(**kwargs),
                    'AverageOfficerDispatchesWithin1kmRadiusInPast48Hours': dispatches.AverageOfficerDispatchesWithin1kmRadiusInPast48Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin100mRadiusInPast1Hour': dispatches.MaximumOfficerDispatchesWithin100mRadiusInPast1Hour(**kwargs),
                    'MaximumOfficerDispatchesWithin100mRadiusInPast3Hours': dispatches.MaximumOfficerDispatchesWithin100mRadiusInPast3Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin100mRadiusInPast6Hours': dispatches.MaximumOfficerDispatchesWithin100mRadiusInPast6Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin100mRadiusInPast24Hours': dispatches.MaximumOfficerDispatchesWithin100mRadiusInPast24Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin100mRadiusInPast48Hours': dispatches.MaximumOfficerDispatchesWithin100mRadiusInPast48Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin500mRadiusInPast1Hour': dispatches.MaximumOfficerDispatchesWithin500mRadiusInPast1Hour(**kwargs),
                    'MaximumOfficerDispatchesWithin500mRadiusInPast3Hours': dispatches.MaximumOfficerDispatchesWithin500mRadiusInPast3Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin500mRadiusInPast6Hours': dispatches.MaximumOfficerDispatchesWithin500mRadiusInPast6Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin500mRadiusInPast24Hours': dispatches.MaximumOfficerDispatchesWithin500mRadiusInPast24Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin500mRadiusInPast48Hours': dispatches.MaximumOfficerDispatchesWithin500mRadiusInPast48Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin1kmRadiusInPast1Hour': dispatches.MaximumOfficerDispatchesWithin1kmRadiusInPast1Hour(**kwargs),
                    'MaximumOfficerDispatchesWithin1kmRadiusInPast3Hours': dispatches.MaximumOfficerDispatchesWithin1kmRadiusInPast3Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin1kmRadiusInPast6Hours': dispatches.MaximumOfficerDispatchesWithin1kmRadiusInPast6Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin1kmRadiusInPast24Hours': dispatches.MaximumOfficerDispatchesWithin1kmRadiusInPast24Hours(**kwargs),
                    'MaximumOfficerDispatchesWithin1kmRadiusInPast48Hours': dispatches.MaximumOfficerDispatchesWithin1kmRadiusInPast48Hours(**kwargs)
                  }

    #dict_lookup = {'dummyfeature': officers.dummyfeature(**kwargs),
    #                'ArrestCount1Yr': officers.ArrestCount1Yr(**kwargs),
    #                'ArrestCountCareer': officers.ArrestCountCareer(**kwargs),
    #                'height_weight': officers.HeightWeight(**kwargs),
    #                'education': officers.Education(**kwargs),
    #                'daysexperience': officers.DaysExperience(**kwargs),
    #                'yearsexperience': officers.YrsExperience(**kwargs),
    #                'malefemale': officers.MaleFemale(**kwargs),
    #                'race': officers.Race(**kwargs),
    #                'officerage': officers.Age(**kwargs),
    #                'officerageathire': officers.AgeAtHire(**kwargs),
    #                'maritalstatus': officers.MaritalStatus(**kwargs),
    #                'numrecentarrests': officers.NumRecentArrests(**kwargs),
    #                'careerNPCarrests': officers.NPCArrests(**kwargs),
    #                '1yrNPCarrests': officers.NPCArrests(**kwargs),
    #                'careerdiscarrests': officers.DiscArrests(**kwargs),
    #                '1yrdiscarrests': officers.DiscArrests(**kwargs),
    #                'arresttod': officers.AverageTimeOfDayArrests(**kwargs),
    #                'arresteeage': officers.AvgAgeArrests(**kwargs),
    #                'disconlyarrests': officers.DiscOnlyArrestsCount(**kwargs),
    #                'arrestratedelta': officers.ArrestRateDelta(**kwargs),
    #                'arresttimeseries': officers.ArrestTimeSeries(**kwargs),
    #                'arrestcentroids': officers.ArrestCentroids(**kwargs),
    #                'careernpccitations': officers.NPCCitations(**kwargs),
    #                '1yrnpccitations': officers.NPCCitations(**kwargs),
    #                'careercitations': officers.Citations(**kwargs),
    #                '1yrcitations': officers.Citations(**kwargs),
    #                'numsuicides': officers.YearNumSuicides(**kwargs),
    #                'numjuveniles': officers.YearNumJuvenileVictim(**kwargs),
    #                'numdomesticviolence': officers.YearNumDomesticViolence(**kwargs),
    #                'numhate': officers.YearNumHate(**kwargs),
    #                'numnarcotics': officers.YearNumNarcotics(**kwargs),
    #                'numgang': officers.YearNumGang(**kwargs),
    #                'numpersweaps': officers.YearNumPersWeaps(**kwargs),
    #                'numgunknife': officers.YearNumGunKnife(**kwargs),
    #                'avgagevictims': officers.AvgAgeVictims(**kwargs),
    #                'minagevictims': officers.MinAgeVictims(**kwargs),
    #                'careerficount': officers.FICount(**kwargs),
    #                '1yrficount': officers.FICount(**kwargs),
    #                'careernontrafficficount': officers.NonTrafficFICount(**kwargs),
    #                '1yrnontrafficficount': officers.NonTrafficFICount(**kwargs),
    #                'careerhighcrimefi': officers.HighCrimeAreaFI(**kwargs),
    #                '1yrhighcrimefi': officers.HighCrimeAreaFI(**kwargs),
    #                '1yrloiterfi': officers.LoiterFI(**kwargs),
    #                'careerloiterfi': officers.LoiterFI(**kwargs),
    #                'careerblackfi': officers.CareerBlackFI(**kwargs),
    #                'careerwhitefi': officers.CareerWhiteFI(**kwargs),
    #                'avgsuspectagefi': officers.FIAvgSuspectAge(**kwargs),
    #                'avgtimeofdayfi': officers.FIAvgTimeOfDay(**kwargs),
    #                'fitimeseries': officers.FITimeseries(**kwargs),
    #                'careercadstats': officers.CADStatistics(**kwargs),
    #                '1yrcadstats': officers.CADStatistics(**kwargs),
    #                'careercadterms': officers.CountCADTerminationTypes(**kwargs),
    #                '1yrcadterms': officers.CountCADTerminationTypes(**kwargs),
    #                'careerelectivetrain': officers.ElectHoursTrain(**kwargs),
    #                '1yrelectivetrain': officers.ElectHoursTrain(**kwargs),
    #                'careerhourstrain': officers.HoursTrain(**kwargs),
    #                '1yrhourstrain': officers.HoursTrain(**kwargs),
    #                'careerworkouthours': officers.HoursPhysFit(**kwargs),
    #                '1yrworkouthours': officers.HoursPhysFit(**kwargs),
    #                'careerrochours': officers.HoursROCTrain(**kwargs),
    #                '1yrrochours': officers.HoursROCTrain(**kwargs),
    #                'careerproftrain': officers.HoursProfTrain(**kwargs),
    #                '1yrproftrain': officers.HoursProfTrain(**kwargs),
    #                'careertrafficstopnum': officers.NumTrafficStops(**kwargs),
    #                '1yrtrafficstopnum': officers.NumTrafficStops(**kwargs),
    #                'careerdomvioltrain': officers.HoursDomViolTrain(**kwargs),
    #                '1yrdomvioltrain': officers.HoursDomViolTrain(**kwargs),
    #                'careermilitarytrain': officers.HoursMilitaryReturn(**kwargs),
    #                '1yrmilitarytrain': officers.HoursMilitaryReturn(**kwargs),
    #                'careertasertrain': officers.HoursTaserTrain(**kwargs),
    #                '1yrtasertrain': officers.HoursTaserTrain(**kwargs),
    #                'careerbiastrain': officers.HoursBiasTrain(**kwargs),
    #                '1yrbiastrain': officers.HoursBiasTrain(**kwargs),
    #                'careerforcetrain': officers.HoursForceTrain(**kwargs),
    #                '1yrforcetrain': officers.HoursForceTrain(**kwargs),
    #                'careertsuofarr': officers.NumTStopRunTagUOFOrArrest(**kwargs),
    #                '1yrtsuofarr': officers.NumTStopRunTagUOFOrArrest(**kwargs),
    #                'careerforcetraffic': officers.NumTrafficStopsForce(**kwargs),
    #                '1yrforcetraffic': officers.NumTrafficStopsForce(**kwargs),
    #                'careertsblackdaynight': officers.TSPercBlackDayNight(**kwargs),
    #                '1yrtsblackdaynight': officers.TSPercBlackDayNight(**kwargs),
    #                '1yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
    #                '3yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
    #                '5yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
    #                'careertrafstopresist': officers.NumTrafficStopsResist(**kwargs),
    #                '1yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
    #                '3yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
    #                '5yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
    #                'careertrafstopsearch': officers.TrafficStopsSearch(**kwargs),
    #                '1yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
    #                '3yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
    #                '5yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
    #                'careertrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
    #                '1yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
    #                '3yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
    #                '5yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
    #                'careertrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
    #                '1yrtrafstopresult': officers.TrafficStopResult(**kwargs),
    #                '3yrtrafstopresult': officers.TrafficStopResult(**kwargs),
    #                '5yrtrafstopresult': officers.TrafficStopResult(**kwargs),
    #                'careertrafstopresult': officers.TrafficStopResult(**kwargs),
    #                '1yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
    #                '3yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
    #                '5yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
    #                'careertrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
    #                '1yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
    #                '3yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
    #                '5yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
    #                'careertrafstopbygender': officers.TrafficStopFracGender(**kwargs),
    #                'trafficstoptimeseries': officers.TrafficStopTimeSeries(**kwargs),
    #                '1yreiswarnings': officers.EISWarningsCount(**kwargs),
    #                '5yreiswarnings': officers.EISWarningsCount(**kwargs),
    #                'careereiswarnings': officers.EISWarningsCount(**kwargs),
    #                '1yreiswarningtypes': officers.EISWarningByTypeFrac(**kwargs),
    #                'careereiswarningtypes': officers.EISWarningByTypeFrac(**kwargs),
    #                '1yreiswarninginterventions': officers.EISWarningInterventionFrac(**kwargs),
    #                'careereiswarninginterventions': officers.EISWarningInterventionFrac(**kwargs),
    #                '1yrextradutyhours': officers.ExtraDutyHours(**kwargs),
    #                'careerextradutyhours': officers.ExtraDutyHours(**kwargs),
    #                '1yrextradutyneighb1': officers.ExtraDutyNeighborhoodFeatures1(**kwargs),
    #                'careerextradutyneighb1': officers.ExtraDutyNeighborhoodFeatures1(**kwargs),
    #                '1yrextradutyneighb2': officers.ExtraDutyNeighborhoodFeatures2(**kwargs),
    #                'careerextradutyneighb2': officers.ExtraDutyNeighborhoodFeatures2(**kwargs),
    #                '1yrneighb1': officers.AvgNeighborhoodFeatures1(**kwargs),
    #                'careerneighb1': officers.AvgNeighborhoodFeatures1(**kwargs),
    #                '1yrneighb2': officers.AvgNeighborhoodFeatures2(**kwargs),
    #                'careerneighb2': officers.AvgNeighborhoodFeatures2(**kwargs),
    #                '1yrprioralladverse': officers.CountPriorAdverse(**kwargs),
    #                'careerprioralladverse': officers.CountPriorAdverse(**kwargs),
    #                '1yrprioraccident': officers.CountPriorAccident(**kwargs),
    #                'careerprioraccident': officers.CountPriorAccident(**kwargs),
    #                '1yrnumfilteredadverse': officers.CountPriorFilteredAdverse(**kwargs),
    #                'careernumfilteredadverse': officers.CountPriorFilteredAdverse(**kwargs),
    #                '1yrroccoc': officers.CountRocCOC(**kwargs),
    #                'careerroccoc': officers.CountRocCOC(**kwargs),
    #                '1yrrocia': officers.CountRocIA(**kwargs),
    #                'careerrocia': officers.CountRocIA(**kwargs),
    #                '1yrpreventable': officers.CountPreventable(**kwargs),
    #                'careerpreventable': officers.CountPreventable(**kwargs),
    #                '1yrunjustified': officers.CountUnjustified(**kwargs),
    #                'careerunjustified': officers.CountUnjustified(**kwargs),
    #                '1yrsustaincompl': officers.CountSustainedComplaints(**kwargs),
    #                'careersustaincompl': officers.CountSustainedComplaints(**kwargs),
    #                '1yriaconcerns': officers.IAConcerns(**kwargs),
    #                'careeriaconcerns': officers.IAConcerns(**kwargs),
    #                'careeriarate': officers.IARate(**kwargs),
    #                '1yrdofcounts': officers.DOFTypeCounts(**kwargs),
    #                'careerdofcounts': officers.DOFTypeCounts(**kwargs),
    #                '1yrdirectivecounts': officers.DirectiveViolCounts(**kwargs),
    #                'careerdirectivecounts': officers.DirectiveViolCounts(**kwargs),
    #                '1yriaeventtypes': officers.IAEventTypeCounts(**kwargs),
    #                'careeriaeventtypes': officers.IAEventTypeCounts(**kwargs),
    #                '1yrinterventions': officers.SuspensionCounselingTime(**kwargs),
    #                'careerinterventions': officers.SuspensionCounselingTime(**kwargs),
    #                '1yrweaponsuse': officers.NormalizedCountsWeaponsUse(**kwargs),
    #                'careerweaponsuse': officers.NormalizedCountsWeaponsUse(**kwargs),
    #                '1yrunithistory': officers.CountUnit(**kwargs),
    #                'careerunithistory': officers.CountUnit(**kwargs),
    #                '1yrdivisionhistory': officers.CountDivision(**kwargs),
    #                'careerdivisionhistory': officers.CountDivision(**kwargs),}

    if feature not in dict_lookup.keys():
        raise UnknownFeatureError(feature)

    return dict_lookup[feature]
