import numpy as np
import pdb
import pandas as pd
import yaml
import logging
import sys
import datetime

from . import officers

log = logging.getLogger(__name__)


class UnknownFeatureError(Exception):
    def __init__(self, feature):
        self.feature = feature

    def __str__(self):
        return "Unknown feature: {}".format(self.feature)


def lookup(feature, **kwargs):

    if feature[1:3] == "yr":
        kwargs["feat_time_window"] = int(feature[0])
    else:
        kwargs["feat_time_window"] = 15

    dict_lookup = {'dummyfeature': officers.dummyfeature(**kwargs),
                    'arrest_count_1yr': officers.NumArrestsInPast1yr(**kwargs),
                    'height_weight': officers.HeightWeight(**kwargs),
                    'education': officers.Education(**kwargs),
                    'daysexperience': officers.DaysExperience(**kwargs),
                    'yearsexperience': officers.YrsExperience(**kwargs),
                    'malefemale': officers.MaleFemale(**kwargs),
                    'race': officers.Race(**kwargs),
                    'officerage': officers.Age(**kwargs),
                    'officerageathire': officers.AgeAtHire(**kwargs),
                    'maritalstatus': officers.MaritalStatus(**kwargs),
                    'careerarrests': officers.CareerArrests(**kwargs),
                    #'numrecentarrests': officers.NumRecentArrests(**kwargs),
                    'careerNPCarrests': officers.NPCArrests(**kwargs),
                    '1yrNPCarrests': officers.NPCArrests(**kwargs),
                    'careerdiscarrests': officers.DiscArrests(**kwargs),
                    '1yrdiscarrests': officers.DiscArrests(**kwargs),
                    'arresttod': officers.AvgTimeOfDayArrests(**kwargs),
                    'arresteeage': officers.AvgAgeArrests(**kwargs),
                    'disconlyarrests': officers.DiscOnlyArrestsCount(**kwargs),
                    'arrestratedelta': officers.ArrestRateDelta(**kwargs),
                    'arresttimeseries': officers.ArrestTimeSeries(**kwargs),
                    'arrestcentroids': officers.ArrestCentroids(**kwargs),
                    'careernpccitations': officers.NPCCitations(**kwargs),
                    '1yrnpccitations': officers.NPCCitations(**kwargs),
                    'careercitations': officers.Citations(**kwargs),
                    '1yrcitations': officers.Citations(**kwargs),
                    'numsuicides': officers.YearNumSuicides(**kwargs),
                    'numjuveniles': officers.YearNumJuvenileVictim(**kwargs),
                    'numdomesticviolence': officers.YearNumDomesticViolence(**kwargs),
                    'numhate': officers.YearNumHate(**kwargs),
                    'numnarcotics': officers.YearNumNarcotics(**kwargs),
                    'numgang': officers.YearNumGang(**kwargs),
                    'numpersweaps': officers.YearNumPersWeaps(**kwargs),
                    'numgunknife': officers.YearNumGunKnife(**kwargs),
                    'avgagevictims': officers.AvgAgeVictims(**kwargs),
                    'minagevictims': officers.MinAgeVictims(**kwargs),
                    'careerficount': officers.FICount(**kwargs),
                    '1yrficount': officers.FICount(**kwargs),
                    'careernontrafficficount': officers.NonTrafficFICount(**kwargs),
                    '1yrnontrafficficount': officers.NonTrafficFICount(**kwargs),
                    'careerhighcrimefi': officers.HighCrimeAreaFI(**kwargs),
                    '1yrhighcrimefi': officers.HighCrimeAreaFI(**kwargs),
                    '1yrloiterfi': officers.LoiterFI(**kwargs),
                    'careerloiterfi': officers.LoiterFI(**kwargs),
                    'careerblackfi': officers.CareerBlackFI(**kwargs),
                    'careerwhitefi': officers.CareerWhiteFI(**kwargs),
                    'avgsuspectagefi': officers.FIAvgSuspectAge(**kwargs),
                    'avgtimeofdayfi': officers.FIAvgTimeOfDay(**kwargs),
                    'fitimeseries': officers.FITimeseries(**kwargs),
                    'careercadstats': officers.CADStatistics(**kwargs),
                    '1yrcadstats': officers.CADStatistics(**kwargs),
                    'careercadterms': officers.CountCADTerminationTypes(**kwargs),
                    '1yrcadterms': officers.CountCADTerminationTypes(**kwargs),
                    'careerelectivetrain': officers.ElectHoursTrain(**kwargs),
                    '1yrelectivetrain': officers.ElectHoursTrain(**kwargs),
                    'careerhourstrain': officers.HoursTrain(**kwargs),
                    '1yrhourstrain': officers.HoursTrain(**kwargs),
                    'careerworkouthours': officers.HoursPhysFit(**kwargs),
                    '1yrworkouthours': officers.HoursPhysFit(**kwargs),
                    'careerrochours': officers.HoursROCTrain(**kwargs),
                    '1yrrochours': officers.HoursROCTrain(**kwargs),
                    'careerproftrain': officers.HoursProfTrain(**kwargs),
                    '1yrproftrain': officers.HoursProfTrain(**kwargs),
                    'careertrafficstopnum': officers.NumTrafficStops(**kwargs),
                    '1yrtrafficstopnum': officers.NumTrafficStops(**kwargs),
                    'careerdomvioltrain': officers.HoursDomViolTrain(**kwargs),
                    '1yrdomvioltrain': officers.HoursDomViolTrain(**kwargs),
                    'careermilitarytrain': officers.HoursMilitaryReturn(**kwargs),
                    '1yrmilitarytrain': officers.HoursMilitaryReturn(**kwargs),
                    'careertasertrain': officers.HoursTaserTrain(**kwargs),
                    '1yrtasertrain': officers.HoursTaserTrain(**kwargs),
                    'careerbiastrain': officers.HoursBiasTrain(**kwargs),
                    '1yrbiastrain': officers.HoursBiasTrain(**kwargs),
                    'careerforcetrain': officers.HoursForceTrain(**kwargs),
                    '1yrforcetrain': officers.HoursForceTrain(**kwargs),
                    'careertsuofarr': officers.NumTStopRunTagUOFOrArrest(**kwargs),
                    '1yrtsuofarr': officers.NumTStopRunTagUOFOrArrest(**kwargs),
                    'careerforcetraffic': officers.NumTrafficStopsForce(**kwargs),
                    '1yrforcetraffic': officers.NumTrafficStopsForce(**kwargs),
                    'careertsblackdaynight': officers.TSPercBlackDayNight(**kwargs),
                    '1yrtsblackdaynight': officers.TSPercBlackDayNight(**kwargs),
                    '1yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
                    '3yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
                    '5yrtrafstopresist': officers.NumTrafficStopsResist(**kwargs),
                    'careertrafstopresist': officers.NumTrafficStopsResist(**kwargs),
                    '1yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
                    '3yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
                    '5yrtrafstopsearch': officers.TrafficStopsSearch(**kwargs),
                    'careertrafstopsearch': officers.TrafficStopsSearch(**kwargs),
                    '1yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
                    '3yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
                    '5yrtrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
                    'careertrafstopsearchreason': officers.TrafficStopSearchReason(**kwargs),
                    '1yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
                    '3yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
                    '5yrtrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
                    'careertrafstopruntagreason': officers.TrafficStopRunTagReason(**kwargs),
                    '1yrtrafstopresult': officers.TrafficStopResult(**kwargs),
                    '3yrtrafstopresult': officers.TrafficStopResult(**kwargs),
                    '5yrtrafstopresult': officers.TrafficStopResult(**kwargs),
                    'careertrafstopresult': officers.TrafficStopResult(**kwargs),
                    '1yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
                    '3yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
                    '5yrtrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
                    'careertrafstopbyrace': officers.TrafficStopFracRace(**kwargs),
                    '1yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
                    '3yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
                    '5yrtrafstopbygender': officers.TrafficStopFracGender(**kwargs),
                    'careertrafstopbygender': officers.TrafficStopFracGender(**kwargs),
                    'trafficstoptimeseries': officers.TrafficStopTimeSeries(**kwargs),
                    '1yreiswarnings': officers.EISWarningsCount(**kwargs),
                    '5yreiswarnings': officers.EISWarningsCount(**kwargs),
                    'careereiswarnings': officers.EISWarningsCount(**kwargs),
                    '1yreiswarningtypes': officers.EISWarningByTypeFrac(**kwargs),
                    'careereiswarningtypes': officers.EISWarningByTypeFrac(**kwargs),
                    '1yreiswarninginterventions': officers.EISWarningInterventionFrac(**kwargs),
                    'careereiswarninginterventions': officers.EISWarningInterventionFrac(**kwargs),
                    '1yrextradutyhours': officers.ExtraDutyHours(**kwargs),
                    'careerextradutyhours': officers.ExtraDutyHours(**kwargs),
                    '1yrextradutyneighb1': officers.ExtraDutyNeighborhoodFeatures1(**kwargs),
                    'careerextradutyneighb1': officers.ExtraDutyNeighborhoodFeatures1(**kwargs),
                    '1yrextradutyneighb2': officers.ExtraDutyNeighborhoodFeatures2(**kwargs),
                    'careerextradutyneighb2': officers.ExtraDutyNeighborhoodFeatures2(**kwargs),
                    '1yrneighb1': officers.AvgNeighborhoodFeatures1(**kwargs),
                    'careerneighb1': officers.AvgNeighborhoodFeatures1(**kwargs),
                    '1yrneighb2': officers.AvgNeighborhoodFeatures2(**kwargs),
                    'careerneighb2': officers.AvgNeighborhoodFeatures2(**kwargs),
                    '1yrprioralladverse': officers.CountPriorAdverse(**kwargs),
                    'careerprioralladverse': officers.CountPriorAdverse(**kwargs),
                    '1yrprioraccident': officers.CountPriorAccident(**kwargs),
                    'careerprioraccident': officers.CountPriorAccident(**kwargs),
                    '1yrnumfilteredadverse': officers.CountPriorFilteredAdverse(**kwargs),
                    'careernumfilteredadverse': officers.CountPriorFilteredAdverse(**kwargs),
                    '1yrroccoc': officers.CountRocCOC(**kwargs),
                    'careerroccoc': officers.CountRocCOC(**kwargs),
                    '1yrrocia': officers.CountRocIA(**kwargs),
                    'careerrocia': officers.CountRocIA(**kwargs),
                    '1yrpreventable': officers.CountPreventable(**kwargs),
                    'careerpreventable': officers.CountPreventable(**kwargs),
                    '1yrunjustified': officers.CountUnjustified(**kwargs),
                    'careerunjustified': officers.CountUnjustified(**kwargs),
                    '1yrsustaincompl': officers.CountSustainedComplaints(**kwargs),
                    'careersustaincompl': officers.CountSustainedComplaints(**kwargs),
                    '1yriaconcerns': officers.IAConcerns(**kwargs),
                    'careeriaconcerns': officers.IAConcerns(**kwargs),
                    'careeriarate': officers.IARate(**kwargs),
                    '1yrdofcounts': officers.DOFTypeCounts(**kwargs),
                    'careerdofcounts': officers.DOFTypeCounts(**kwargs),
                    '1yrdirectivecounts': officers.DirectiveViolCounts(**kwargs),
                    'careerdirectivecounts': officers.DirectiveViolCounts(**kwargs),
                    '1yriaeventtypes': officers.IAEventTypeCounts(**kwargs),
                    'careeriaeventtypes': officers.IAEventTypeCounts(**kwargs),
                    '1yrinterventions': officers.SuspensionCounselingTime(**kwargs),
                    'careerinterventions': officers.SuspensionCounselingTime(**kwargs),
                    '1yrweaponsuse': officers.NormalizedCountsWeaponsUse(**kwargs),
                    'careerweaponsuse': officers.NormalizedCountsWeaponsUse(**kwargs),
                    '1yrunithistory': officers.CountUnit(**kwargs),
                    'careerunithistory': officers.CountUnit(**kwargs),
                    '1yrdivisionhistory': officers.CountDivision(**kwargs),
                    'careerdivisionhistory': officers.CountDivision(**kwargs),}


    if feature not in dict_lookup.keys():
        raise UnknownFeatureError(feature)

    return dict_lookup[feature]
