DROP TABLE IF EXISTS staging.internal_affairs_investigations; 
CREATE  TABLE staging.internal_affairs_investigations (
	event_id                                                              int references staging.events_hub(event_id) on delete cascade,                --event id
	incident_type_code                                                    int,                --the kind of incident that took place e.g. DUI, UOF, injury to officer. Includes the severity of the injury if one occurred
	rule_violated_code                                                    int,                --the specific department rule that was violated
	department_defined_investigation_id                                   varchar,            --an id that maps to the original investigation id
	final_ruling_code                                                     int,                --final ruling on the investigation (justified/unjustified/unclear). May have to be generated by us. 
	investigation_supervisor_id                                           int,                --the supervisor who oversaw the investigation
	tactics_concerns_flag                                                 bool,               --if there were any concerns over the investigated officer's use of tactics
	safety_concerns_flag                                                  bool,               --if there were any safety concerns over the officer being investigated
	communications_concerns_flag                                          bool,               --if there were any communication concerns over the officer being investigated
	intervention_type_code                                                int,                --the type of intervention given e.g. None/training/suspension/councelling
	days_suspended                                                        int,                --the number of days suspended (may be 0)
	training_id                                                           int,                --this links to the training table, which describes what training an officer received as a result of the investigation
	date_investigation_started                                            timestamp,          --date that the investigation proceeding began
	date_of_judgement                                                     timestamp,          --date that a judgement was reached
	date_intervention_received                                            timestamp,          --date that an intervention was received. May duplicated what is seen in the training table.
	reprimand_type_code                                                   int,                --the kind of repirmand, e.g. verbal, written, none etc
	reprimand_narrative                                                   text,               --free text field for the reprimand given to the officer, if one is given
	officer_explanation_narrative                                         text,               --
	general_narrative                                                     text                --free text field describing the investigation
);
